import { StyleSheet } from 'react-native';
import {
  radii,
  spacing,
  typography,
  type ThemeColors,
} from '../../constants/theme';
import { useThemedStyles } from '../../hooks/useThemedStyles';

const createStyles = (colors: ThemeColors) =>
  StyleSheet.create({
    rowRTL: { flexDirection: 'row-reverse' },
    textRTL: { textAlign: 'right', writingDirection: 'rtl' },
    centeredTextRTL: { writingDirection: 'rtl' },
    header: {
      minHeight: 76,
      paddingHorizontal: spacing.screen,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    headerButton: {
      width: 44,
      height: 44,
      borderRadius: 22,
      borderWidth: 1,
      borderColor: colors.divider,
      backgroundColor: colors.surface,
      alignItems: 'center',
      justifyContent: 'center',
    },
    headerCenter: { alignItems: 'center', gap: spacing.xs },
    activePill: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      borderWidth: 1,
      borderColor: colors.primary,
      borderRadius: radii.pill,
      paddingHorizontal: spacing.medium,
      paddingVertical: spacing.xs,
      backgroundColor: colors.infoSurface,
    },
    activeDot: {
      width: 6,
      height: 6,
      borderRadius: 3,
      backgroundColor: colors.primary,
    },
    activePillText: {
      ...typography.caption,
      color: colors.primary,
      fontWeight: '700',
    },
    dayText: { ...typography.caption, color: colors.textSecondary },
    content: {
      paddingHorizontal: spacing.screen,
      paddingBottom: 100,
      gap: spacing.large,
    },
    summaryCard: {
      borderRadius: 24,
      borderWidth: 1,
      borderColor: colors.heroBorder,
      backgroundColor: colors.heroBackground,
      padding: spacing.large,
    },
    summaryTopRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: spacing.large,
    },
    summaryCopy: { flex: 1 },
    routineBadge: {
      alignSelf: 'flex-start',
      backgroundColor: colors.iconSurface,
      borderRadius: radii.small,
      borderWidth: 1,
      borderColor: colors.heroBorder,
      paddingHorizontal: spacing.medium,
      paddingVertical: 6,
      marginBottom: spacing.medium,
    },
    routineBadgeRTL: { alignSelf: 'flex-end' },
    routineBadgeText: {
      ...typography.caption,
      color: colors.primary,
      fontWeight: '700',
    },
    summaryTitle: {
      ...typography.headingL,
      color: colors.text,
    },
    percentBox: {
      minWidth: 72,
      minHeight: 72,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: radii.card,
      borderWidth: 1,
      borderColor: colors.heroBorder,
      backgroundColor: colors.background,
    },
    percentValue: {
      ...typography.headingL,
      color: colors.primary,
    },
    percentLabel: {
      ...typography.caption,
      color: colors.textSecondary,
      fontWeight: '700',
    },
    progressHeading: {
      marginTop: spacing.xl,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      gap: spacing.medium,
    },
    progressLabel: {
      ...typography.body,
      color: colors.textSecondary,
      fontWeight: '600',
    },
    progressValue: {
      ...typography.body,
      color: colors.primary,
      fontWeight: '700',
    },
    progressTrack: {
      height: 7,
      backgroundColor: colors.divider,
      borderRadius: 4,
      overflow: 'hidden',
      marginTop: spacing.small,
    },
    progressTrackRTL: { alignItems: 'flex-end' },
    progressFill: {
      height: '100%',
      backgroundColor: colors.primary,
      borderRadius: 4,
    },
    divider: {
      height: StyleSheet.hairlineWidth,
      backgroundColor: colors.divider,
      marginVertical: spacing.xl,
    },
    statsRow: { flexDirection: 'row', gap: spacing.medium },
    statCard: {
      flex: 1,
      alignItems: 'center',
      backgroundColor: colors.background,
      borderRadius: radii.card,
      padding: spacing.medium,
    },
    statLabel: { ...typography.caption, color: colors.textSecondary },
    statValueRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      marginTop: spacing.xs,
    },
    streakValue: {
      ...typography.bodyLarge,
      color: colors.yellow,
    },
    consistencyValue: {
      ...typography.bodyLarge,
      color: colors.green,
    },
    tasksHeading: {
      flexDirection: 'row',
      alignItems: 'center',
      flexWrap: 'wrap',
      gap: spacing.small,
      marginTop: spacing.small,
    },
    tasksTitle: { ...typography.headingM, color: colors.text },
    taskCountBadge: {
      borderRadius: radii.pill,
      paddingHorizontal: spacing.medium,
      paddingVertical: spacing.xs,
      backgroundColor: colors.infoSurface,
    },
    taskCountText: {
      ...typography.caption,
      color: colors.primary,
      fontWeight: '700',
    },
    tapHint: {
      ...typography.caption,
      color: colors.textSecondary,
      marginLeft: 'auto',
    },
    tapHintRTL: { marginLeft: 0, marginRight: 'auto' },
    taskCard: {
      minHeight: 82,
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.medium,
      borderWidth: 1,
      borderColor: colors.divider,
      backgroundColor: colors.surface,
      borderRadius: radii.card,
      padding: spacing.medium,
    },
    nextTaskCard: { borderColor: colors.primary, borderWidth: 2 },
    taskPressed: { opacity: 0.82 },
    taskIcon: {
      width: 48,
      height: 48,
      borderRadius: radii.small,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: colors.heroBorder,
      backgroundColor: colors.iconSurface,
    },
    taskCopy: { flex: 1 },
    taskTitleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      flexWrap: 'wrap',
      gap: spacing.small,
    },
    taskTitle: { ...typography.bodyLarge, color: colors.text, flexShrink: 1 },
    completedTaskTitle: {
      color: colors.textSecondary,
      textDecorationLine: 'line-through',
    },
    taskSubtitle: {
      ...typography.caption,
      color: colors.textSecondary,
      marginTop: spacing.xs,
    },
    doneBadge: {
      borderRadius: 6,
      backgroundColor: colors.successSurface,
      paddingHorizontal: spacing.small,
      paddingVertical: 2,
    },
    doneBadgeText: {
      ...typography.caption,
      color: colors.green,
      fontWeight: '700',
    },
    nextBadge: {
      borderRadius: 6,
      backgroundColor: colors.infoSurface,
      paddingHorizontal: spacing.small,
      paddingVertical: 2,
    },
    nextBadgeText: {
      ...typography.caption,
      color: colors.primary,
      fontWeight: '700',
    },
    check: {
      width: 36,
      height: 36,
      borderRadius: 18,
      borderWidth: 2,
      borderColor: colors.primary,
      alignItems: 'center',
      justifyContent: 'center',
    },
    checked: { backgroundColor: colors.primary },
    tipCard: {
      flexDirection: 'row',
      gap: spacing.medium,
      borderRadius: radii.card,
      borderWidth: 1,
      borderColor: colors.divider,
      backgroundColor: colors.surface,
      padding: spacing.large,
      marginTop: spacing.small,
    },
    tipIcon: {
      width: 38,
      height: 38,
      borderRadius: radii.small,
      backgroundColor: colors.premiumSurface,
      alignItems: 'center',
      justifyContent: 'center',
    },
    tipCopy: { flex: 1 },
    tipTitle: {
      ...typography.body,
      color: colors.text,
      fontWeight: '700',
    },
    tipText: {
      ...typography.body,
      color: colors.textSecondary,
      marginTop: spacing.xs,
    },
    modalBackdrop: {
      flex: 1,
      backgroundColor: colors.overlay,
      justifyContent: 'center',
      paddingHorizontal: spacing.screen,
    },
    menu: {
      borderRadius: radii.card,
      borderWidth: 1,
      borderColor: colors.divider,
      backgroundColor: colors.surface,
      padding: spacing.large,
      shadowColor: colors.shadow,
      shadowOpacity: 0.25,
      shadowRadius: 18,
      elevation: 8,
    },
    menuTitle: { ...typography.headingM, color: colors.text },
    menuCopy: {
      ...typography.body,
      color: colors.textSecondary,
      marginTop: spacing.small,
      marginBottom: spacing.large,
    },
    removeButton: {
      minHeight: 50,
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.medium,
      borderRadius: radii.button,
      backgroundColor: colors.surfaceSecondary,
      paddingHorizontal: spacing.large,
    },
    removeText: {
      ...typography.caption,
      color: colors.red,
      fontWeight: '800',
    },
    cancelButton: { alignItems: 'center', paddingTop: spacing.large },
    cancelText: {
      ...typography.caption,
      color: colors.textSecondary,
      fontWeight: '700',
    },
    emptyPage: { justifyContent: 'center', alignItems: 'center' },
    emptyTitle: {
      ...typography.headingL,
      color: colors.text,
      marginTop: spacing.xl,
    },
    emptyCopy: {
      ...typography.body,
      color: colors.textSecondary,
      textAlign: 'center',
      marginTop: spacing.medium,
    },
    emptyBackButtonRTL: { alignSelf: 'flex-end' },
  });

export default function useStyles() {
  return useThemedStyles(createStyles);
}
