import { StyleSheet } from 'react-native';
import {
  radii,
  spacing,
  typography,
  type ThemeColors,
} from '../../constants/theme';
import { useThemedStyles } from '../../hooks/useThemedStyles';

const createStyles = (colors: ThemeColors) =>
  StyleSheet.create({
    header: {
      height: 72,
      paddingHorizontal: spacing.screen,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    pageTitle: {
      ...typography.headingL,
      color: colors.text,
      letterSpacing: 1.3,
    },
    rowRTL: { flexDirection: 'row-reverse' },
    textRTL: { textAlign: 'right', writingDirection: 'rtl' },
    centeredTextRTL: { writingDirection: 'rtl' },
    horizontalCardRTL: { marginHorizontal: spacing.small },
    page: { flex: 1 },
    section: {
      ...typography.caption,
      color: colors.textSecondary,
      fontWeight: '700',
      letterSpacing: 1.1,
      paddingHorizontal: spacing.screen,
      marginBottom: spacing.medium,
    },
    recommendedSection: { marginHorizontal: -spacing.screen },
    activeCarouselList: { height: 182, marginBottom: spacing.xl },
    carouselList: { height: 190 },
    carousel: { paddingHorizontal: spacing.screen },
    art: {
      width: 285,
      height: 190,
      borderRadius: 22,
      overflow: 'hidden',
      padding: spacing.large,
      justifyContent: 'flex-end',
    },
    compact: { width: '100%', height: 138 },
    orb: {
      position: 'absolute',
      width: 190,
      height: 190,
      borderRadius: 95,
      right: -40,
      top: -65,
      opacity: 0.8,
    },
    orbRTL: { right: undefined, left: -40 },
    artIcon: {
      position: 'absolute',
      right: 30,
      top: 30,
      width: 64,
      height: 64,
      borderRadius: 32,
      backgroundColor: colors.artworkIconSurface,
      alignItems: 'center',
      justifyContent: 'center',
    },
    artIconRTL: { right: undefined, left: 30 },
    journeyImage: {
      width: 58,
      height: 58,
      borderRadius: 29,
    },
    compactJourneyImage: {
      width: 46,
      height: 46,
      borderRadius: 23,
    },
    cardCopy: { maxWidth: '84%' },
    cardCopyRTL: { alignSelf: 'flex-end' },
    badge: {
      alignSelf: 'flex-start',
      borderRadius: 12,
      paddingHorizontal: 9,
      paddingVertical: 4,
      backgroundColor: colors.artworkOverlay,
      marginBottom: spacing.small,
    },
    badgeRTL: { alignSelf: 'flex-end' },
    detailHeroBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.small,
      paddingHorizontal: spacing.medium,
      paddingVertical: 6,
      marginBottom: 0,
    },
    badgeText: {
      ...typography.caption,
      color: colors.onPrimary,
      fontWeight: '700',
    },
    cardTitle: { ...typography.headingM, color: colors.onPrimary },
    compactTitle: { fontSize: 17, lineHeight: 22, maxWidth: '72%' },
    detailCardCopy: {
      flex: 1,
      maxWidth: '72%',
      justifyContent: 'space-between',
      padding: spacing.large,
    },
    detailHeroTitle: {
      fontSize: 22,
      lineHeight: 29,
      fontWeight: '700',
    },
    allTitle: { marginTop: spacing.xl },
    list: { paddingHorizontal: spacing.screen, paddingBottom: 110 },
    detailPage: {  },
    detailHeader: {
      minHeight: 72,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    detailHeaderButton: {
      width: 44,
      height: 44,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.divider,
      backgroundColor: colors.surface,
      alignItems: 'center',
      justifyContent: 'center',
    },
    detailHeaderSpacer: {
      width: 44,
      height: 44,
    },
    detailHeaderTitle: {
      ...typography.bodyLarge,
      color: colors.text,
      letterSpacing: 3,
    },
    detailPageArt: {
      width: '100%',
      height: 210,
      borderRadius: 22,
      padding: 0,
    },
    detailBackgroundImage: {
      position: 'absolute',
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      width: '100%',
      height: '100%',
    },
    detailArtworkOverlay: {
      position: 'absolute',
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      backgroundColor: colors.artworkOverlay,
    },
    detailTitle: {
      fontSize: 22,
      lineHeight: 28,
      fontWeight: '700',
      color: colors.text,
      marginTop: spacing.xl,
    },
    detailMetadata: {
      flexDirection: 'row',
      alignItems: 'center',
      flexWrap: 'wrap',
      gap: spacing.small,
      marginTop: spacing.medium,
    },
    detailMetadataItem: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    detailDuration: {
      ...typography.body,
      color: colors.primary,
      fontWeight: '600',
    },
    detailMetadataText: {
      ...typography.body,
      color: colors.textSecondary,
    },
    metadataDot: {
      ...typography.body,
      color: colors.muted,
    },
    dailyHabitsBadge: {
      borderRadius: radii.small,
      borderWidth: 1,
      borderColor: colors.green,
      backgroundColor: colors.surface,
      paddingHorizontal: spacing.medium,
      paddingVertical: spacing.xs,
    },
    dailyHabitsText: {
      ...typography.caption,
      color: colors.green,
      fontWeight: '600',
    },
    description: {
      ...typography.body,
      color: colors.textSecondary,
      fontSize: 16,
      lineHeight: 25,
      marginTop: spacing.large,
      marginBottom: spacing.xxl,
    },
    detailSectionRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: spacing.large,
    },
    detailSection: {
      ...typography.caption,
      color: colors.textSecondary,
      fontWeight: '700',
      letterSpacing: 1.1,
    },
    habitCountBadge: {
      borderRadius: radii.pill,
      borderWidth: 1,
      borderColor: colors.primary,
      paddingHorizontal: spacing.medium,
      paddingVertical: spacing.xs,
    },
    habitCountText: {
      ...typography.caption,
      color: colors.primary,
      fontWeight: '600',
    },
    habit: {
      minHeight: 82,
      borderRadius: radii.card,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.divider,
      padding: spacing.large,
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.medium,
    },
    habitNumber: {
      width: 30,
      height: 30,
      borderRadius: 15,
      backgroundColor: colors.iconSurface,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: colors.primary,
    },
    habitNumberText: {
      ...typography.caption,
      color: colors.primary,
      fontWeight: '700',
    },
    habitCopy: { flex: 1 },
    habitText: { ...typography.bodyLarge, color: colors.text },
    habitGuidance: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      marginTop: spacing.xs,
    },
    habitGuidanceText: {
      ...typography.caption,
      color: colors.textSecondary,
    },
    habitCheck: {
      width: 34,
      height: 34,
      borderRadius: 17,
      borderWidth: 1,
      borderColor: colors.primary,
      backgroundColor: colors.iconSurface,
      alignItems: 'center',
      justifyContent: 'center',
    },
    info: {
      flexDirection: 'row',
      gap: spacing.medium,
      padding: spacing.large,
      borderRadius: radii.card,
      backgroundColor: colors.surfaceSecondary,
      marginTop: spacing.xl,
    },
    infoText: { ...typography.caption, color: colors.textSecondary, flex: 1 },
    start: { marginTop: spacing.xl },
  });

export default function useStyles() {
  return useThemedStyles(createStyles);
}
