import { StyleSheet } from 'react-native';
import {
  radii,
  spacing,
  typography,
  type ThemeColors,
} from '../../constants/theme';
import { useThemedStyles } from '../../hooks/useThemedStyles';

const createStyles = (colors: ThemeColors) =>
  StyleSheet.create({
    header: {
      height: 72,
      paddingHorizontal: spacing.screen,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    pageTitle: {
      ...typography.headingL,
      color: colors.text,
      letterSpacing: 1.3,
    },
    page: { flex: 1 },
    section: {
      ...typography.caption,
      color: colors.textSecondary,
      fontWeight: '700',
      letterSpacing: 1.1,
      paddingHorizontal: spacing.screen,
      marginBottom: spacing.medium,
    },
    recommendedSection: { marginHorizontal: -spacing.screen },
    carouselList: { height: 190 },
    carousel: { paddingHorizontal: spacing.screen },
    art: {
      width: 285,
      height: 190,
      borderRadius: 22,
      overflow: 'hidden',
      padding: spacing.large,
      justifyContent: 'flex-end',
    },
    compact: { width: '100%', height: 138 },
    orb: {
      position: 'absolute',
      width: 190,
      height: 190,
      borderRadius: 95,
      right: -40,
      top: -65,
      opacity: 0.8,
    },
    artIcon: {
      position: 'absolute',
      right: 30,
      top: 30,
      width: 64,
      height: 64,
      borderRadius: 32,
      backgroundColor: colors.artworkIconSurface,
      alignItems: 'center',
      justifyContent: 'center',
    },
    cardCopy: { maxWidth: '84%' },
    badge: {
      alignSelf: 'flex-start',
      borderRadius: 12,
      paddingHorizontal: 9,
      paddingVertical: 4,
      backgroundColor: colors.artworkOverlay,
      marginBottom: spacing.small,
    },
    badgeText: {
      ...typography.caption,
      color: colors.onPrimary,
      fontWeight: '700',
    },
    cardTitle: { ...typography.headingM, color: colors.onPrimary },
    compactTitle: { fontSize: 17, lineHeight: 22, maxWidth: '72%' },
    explore: {
      flexDirection: 'row',
      gap: spacing.small,
      alignItems: 'center',
      marginTop: spacing.medium,
    },
    exploreText: {
      ...typography.caption,
      color: colors.onPrimary,
      fontWeight: '700',
    },
    allTitle: { marginTop: spacing.xl },
    list: { paddingHorizontal: spacing.screen, paddingBottom: 110 },
    detailPage: { paddingBottom: 40 },
    detailPageArt: {},
    detailTitle: {
      ...typography.headingL,
      color: colors.text,
      marginTop: spacing.xl,
    },
    detailDuration: {
      ...typography.body,
      color: colors.primary,
      fontWeight: '600',
      marginTop: spacing.small,
    },
    description: {
      ...typography.body,
      color: colors.textSecondary,
      marginVertical: spacing.xl,
    },
    habits: { gap: spacing.small, marginBottom: spacing.xl },
    detailSection: {
      ...typography.caption,
      color: colors.textSecondary,
      fontWeight: '700',
      letterSpacing: 1.1,
      marginBottom: spacing.medium,
    },
    habit: {
      minHeight: 58,
      borderRadius: radii.button,
      backgroundColor: colors.surface,
      padding: spacing.medium,
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.medium,
    },
    habitNumber: {
      width: 30,
      height: 30,
      borderRadius: 15,
      backgroundColor: colors.iconSurface,
      alignItems: 'center',
      justifyContent: 'center',
    },
    habitNumberText: {
      ...typography.caption,
      color: colors.primary,
      fontWeight: '700',
    },
    habitText: { ...typography.bodyLarge, color: colors.text, flex: 1 },
    info: {
      flexDirection: 'row',
      gap: spacing.medium,
      padding: spacing.large,
      borderRadius: radii.card,
      backgroundColor: colors.surfaceSecondary,
      marginTop: spacing.xl,
    },
    infoText: { ...typography.caption, color: colors.textSecondary, flex: 1 },
    start: { marginTop: spacing.xl },
  });

export default function useStyles() {
  return useThemedStyles(createStyles);
}
