import { StyleSheet } from 'react-native';
import { colors, radii, spacing, typography } from '../../constants/theme';

const styles = StyleSheet.create({
  header: {
    height: 72,
    paddingHorizontal: spacing.screen,
    justifyContent: 'center',
  },
  headerPad: { paddingHorizontal: spacing.screen },
  pageTitle: { ...typography.headingL, color: colors.text, letterSpacing: 1.3 },
  page: { paddingHorizontal: spacing.screen, paddingBottom: 120 },
  backup: {
    minHeight: 82,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.medium,
    padding: spacing.large,
    backgroundColor: colors.surface,
    borderRadius: radii.card,
  },
  backupIcon: {
    width: 48,
    height: 48,
    borderRadius: 16,
    backgroundColor: '#25344A',
    alignItems: 'center',
    justifyContent: 'center',
  },
  copy: { flex: 1 },
  backupTitle: { ...typography.bodyLarge, color: colors.text },
  subtitle: {
    ...typography.caption,
    color: colors.textSecondary,
    marginTop: 3,
  },
  premium: {
    minHeight: 94,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.large,
    padding: spacing.large,
    backgroundColor: colors.selectedBlue,
    borderRadius: radii.card,
    marginTop: spacing.medium,
  },
  premiumTitle: { ...typography.headingM, color: colors.text },
  premiumSubtitle: { ...typography.caption, color: '#D9E7FF' },
  section: {
    ...typography.caption,
    color: colors.textSecondary,
    fontWeight: '700',
    letterSpacing: 1,
    marginTop: spacing.xl,
    marginBottom: spacing.medium,
  },
  sectionNoMargin: {
    ...typography.caption,
    color: colors.textSecondary,
    fontWeight: '700',
    letterSpacing: 1,
  },
  rows: { gap: spacing.small },
  version: {
    ...typography.caption,
    color: colors.muted,
    textAlign: 'center',
    marginTop: spacing.xxl,
  },
  settingsPage: {
    paddingHorizontal: spacing.screen,
    paddingBottom: 40,
    gap: spacing.small,
  },
  notice: {
    flexDirection: 'row',
    gap: spacing.medium,
    padding: spacing.large,
    borderRadius: radii.card,
    backgroundColor: '#17243C',
    marginBottom: spacing.medium,
  },
  noticeText: { ...typography.caption, color: colors.textSecondary, flex: 1 },
  choiceRow: {
    height: 46,
    marginHorizontal: -4,
    marginBottom: spacing.small,
  },
  choiceCell: { flex: 1, paddingHorizontal: 4 },
  choice: {
    flex: 1,
    height: 46,
    borderRadius: radii.button,
    backgroundColor: colors.surfaceSecondary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  choiceActive: { backgroundColor: colors.selectedBlue },
  choiceText: { ...typography.body, color: colors.textSecondary },
  choiceTextActive: { color: colors.text, fontWeight: '600' },
  settingsIntro: {
    ...typography.body,
    color: colors.textSecondary,
    marginBottom: spacing.large,
  },
  language: {
    height: 58,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.medium,
    paddingHorizontal: spacing.large,
    borderRadius: radii.button,
    backgroundColor: colors.surface,
  },
  languageActive: { backgroundColor: colors.selectedBlue },
  languageList: { height: 322 },
  languageText: { ...typography.bodyLarge, color: colors.text, flex: 1 },
  languageCheck: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: colors.text,
    alignItems: 'center',
    justifyContent: 'center',
  },
  feedbackTitle: {
    ...typography.headingL,
    color: colors.text,
    marginTop: spacing.xl,
  },
  character: {
    ...typography.caption,
    color: colors.muted,
    textAlign: 'right',
    marginTop: spacing.small,
  },
  send: { marginTop: 'auto', marginBottom: spacing.xl },
  sent: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  sentIcon: {
    width: 78,
    height: 78,
    borderRadius: 39,
    backgroundColor: colors.selectedBlue,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sentTitle: {
    ...typography.headingL,
    color: colors.text,
    marginTop: spacing.xl,
  },
  sentText: {
    ...typography.body,
    color: colors.textSecondary,
    textAlign: 'center',
    marginTop: spacing.small,
  },
  done: { alignSelf: 'stretch', marginTop: spacing.xl },
  premiumPage: { paddingBottom: 40 },
  premiumHero: { alignItems: 'center', paddingVertical: spacing.xxl },
  crownCircle: {
    width: 104,
    height: 104,
    borderRadius: 52,
    backgroundColor: '#3A321D',
    borderWidth: 1,
    borderColor: '#675625',
    alignItems: 'center',
    justifyContent: 'center',
  },
  premiumHeroTitle: {
    ...typography.headingXL,
    color: colors.text,
    textAlign: 'center',
    marginTop: spacing.xl,
  },
  premiumHeroText: {
    ...typography.body,
    color: colors.textSecondary,
    textAlign: 'center',
    marginTop: spacing.small,
  },
  benefits: { height: 172, marginBottom: spacing.xl },
  benefit: { flexDirection: 'row', alignItems: 'center', gap: spacing.medium },
  benefitCheck: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: colors.selectedBlue,
    alignItems: 'center',
    justifyContent: 'center',
  },
  benefitText: { ...typography.bodyLarge, color: colors.text },
  priceNotice: {
    padding: spacing.large,
    borderRadius: radii.card,
    backgroundColor: colors.surface,
    marginBottom: spacing.xl,
  },
  priceNoticeTitle: { ...typography.bodyLarge, color: colors.text },
  priceNoticeText: {
    ...typography.caption,
    color: colors.textSecondary,
    marginTop: spacing.xs,
  },
  legal: {
    ...typography.caption,
    color: colors.muted,
    textAlign: 'center',
    marginTop: spacing.medium,
  },
});

export default styles;
