import { StyleSheet } from 'react-native';
import {
  radii,
  spacing,
  typography,
  type ThemeColors,
} from '../../constants/theme';
import { useThemedStyles } from '../../hooks/useThemedStyles';

const TIME_OPTION_HEIGHT = 44;
const TIME_OPTION_ROW_HEIGHT = TIME_OPTION_HEIGHT + spacing.xs * 2;

const createStyles = (colors: ThemeColors) =>
  StyleSheet.create({
    headerPad: { paddingHorizontal: spacing.screen },
    todayTop: {
      minHeight: 92,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    eyebrow: {
      ...typography.caption,
      color: colors.primary,
      fontWeight: '700',
      letterSpacing: 1.4,
    },
    dateTitle: { ...typography.headingXL, color: colors.text },
    progressText: {
      ...typography.caption,
      color: colors.textSecondary,
      marginTop: 2,
    },
    plus: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: colors.primary,
      alignItems: 'center',
      justifyContent: 'center',
    },
    dateStrip: {
      height: 68,
      flexGrow: 0,
      flexShrink: 0,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderColor: colors.divider,
    },
    dateStripContent: { paddingHorizontal: spacing.small },
    dateCell: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 3,
      borderBottomWidth: 3,
      borderBottomColor: colors.transparent,
    },
    dateListCell: { flex: 0, height: '100%' },
    dateActive: { borderBottomColor: colors.primary },
    dayName: { fontSize: 10, color: colors.muted, fontWeight: '700' },
    dateNumberCircle: {
      width: 28,
      height: 28,
      borderRadius: 999,
      overflow: 'hidden',
      alignItems: 'center',
      justifyContent: 'center',
    },
    dateNumberCircleActive: {
      width: 28,
      height: 28,
      borderRadius: 999,
      backgroundColor: colors.primary,
    },
    dayNumber: { ...typography.bodyLarge, color: colors.textSecondary },
    activeDayNumber: { color: colors.onPrimary },
    dateProgressTrack: {
      width: 18,
      height: 3,
      overflow: 'hidden',
      borderRadius: 2,
      backgroundColor: colors.divider,
    },
    dateProgressFill: {
      height: 3,
      borderRadius: 2,
      backgroundColor: colors.yellow,
    },
    dateProgressPerfect: { backgroundColor: colors.green },
    activeText: { color: colors.text },
    accentActiveText: { color: colors.onPrimary },
    content: { paddingHorizontal: spacing.screen, paddingBottom: 110 },
    filterList: { height: 72 },
    filters: { paddingVertical: spacing.large },
    filter: {
      height: 40,
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.small,
      paddingHorizontal: spacing.medium,
      borderRadius: 20,
      backgroundColor: colors.surface,
    },
    filterActive: { backgroundColor: colors.selectedBlue },
    filterText: {
      ...typography.caption,
      color: colors.textSecondary,
      fontWeight: '700',
    },
    sectionRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: spacing.medium,
    },
    sectionTitle: {
      ...typography.bodyLarge,
      color: colors.text,
      letterSpacing: 1,
    },
    finishedSectionRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginTop: spacing.xl,
      paddingTop: spacing.large,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: colors.divider,
    },
    finishedSectionTitle: {
      ...typography.bodyLarge,
      color: colors.textSecondary,
      letterSpacing: 1,
    },
    count: { ...typography.caption, color: colors.textSecondary },
    skeletonCard: {
      minHeight: 84,
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.medium,
      padding: spacing.large,
      borderRadius: radii.card,
      backgroundColor: colors.surfaceSecondary,
      opacity: 0.72,
    },
    skeletonCheckbox: {
      width: 30,
      height: 30,
      borderRadius: 15,
      backgroundColor: colors.divider,
    },
    skeletonCopy: { flex: 1, gap: spacing.small },
    skeletonTitle: {
      width: '68%',
      height: 14,
      borderRadius: 7,
      backgroundColor: colors.divider,
    },
    skeletonSubtitle: {
      width: '34%',
      height: 10,
      borderRadius: 5,
      backgroundColor: colors.divider,
    },
    skeletonMenu: {
      width: 24,
      height: 8,
      borderRadius: 4,
      backgroundColor: colors.divider,
    },
    habitList: { flex: 1 },
    empty: { alignItems: 'center', paddingVertical: spacing.xxl },
    emptyTitle: {
      ...typography.headingM,
      color: colors.text,
      marginTop: spacing.medium,
    },
    emptyText: {
      ...typography.body,
      color: colors.textSecondary,
      marginTop: spacing.xs,
      textAlign: 'center',
    },
    create: { marginTop: spacing.xl },
    todayButtonContainer: {
      position: 'absolute',
      right: spacing.screen,
      bottom: spacing.large,
      zIndex: 10,
    },
    todayButton: {
      height: 44,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: spacing.xs,
      paddingHorizontal: spacing.large,
      borderRadius: radii.pill,
      backgroundColor: colors.darkBlue,
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.28,
      shadowRadius: 8,
      elevation: 8,
    },
    todayButtonPressed: { opacity: 0.82 },
    todayButtonText: {
      ...typography.body,
      color: colors.onPrimary,
      fontWeight: '700',
    },
    backdrop: { flex: 1, backgroundColor: colors.overlay },
    popover: {
      position: 'absolute',
      width: 190,
      padding: spacing.small,
      borderRadius: radii.button,
      backgroundColor: colors.surfaceSecondary,
      shadowColor: colors.shadow,
      shadowOpacity: 0.35,
      shadowRadius: 12,
      elevation: 12,
    },
    menuItem: {
      height: 48,
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.medium,
      paddingHorizontal: spacing.medium,
    },
    menuText: {
      ...typography.caption,
      color: colors.text,
      fontWeight: '700',
      letterSpacing: 0.7,
    },
    sheetBackdrop: {
      flex: 1,
      backgroundColor: colors.overlay,
      justifyContent: 'flex-end',
    },
    sheet: {
      padding: spacing.screen,
      paddingBottom: 38,
      gap: spacing.large,
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      backgroundColor: colors.surface,
    },
    sheetHandle: {
      width: 42,
      height: 4,
      alignSelf: 'center',
      borderRadius: 2,
      backgroundColor: colors.muted,
    },
    sheetTop: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    sheetTitle: { ...typography.headingM, color: colors.text },
    form: { paddingBottom: 40, gap: spacing.large },
    editActionsButton: {
      width: 40,
      height: 40,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 20,
    },
    editActionsBackdrop: {
      flex: 1,
      backgroundColor: colors.overlay,
    },
    editActionsMenu: {
      position: 'absolute',
      right: spacing.screen,
      width: 224,
      overflow: 'hidden',
      borderRadius: radii.button,
      backgroundColor: colors.surfaceSecondary,
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.35,
      shadowRadius: 12,
      elevation: 12,
    },
    editActionItem: {
      minHeight: 54,
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.medium,
      paddingHorizontal: spacing.large,
    },
    editActionText: {
      ...typography.caption,
      color: colors.text,
      fontWeight: '700',
      letterSpacing: 0.5,
    },
    editActionDangerText: {
      ...typography.caption,
      color: colors.red,
      fontWeight: '700',
      letterSpacing: 0.5,
    },
    editActionDivider: {
      height: StyleSheet.hairlineWidth,
      backgroundColor: colors.divider,
      marginHorizontal: spacing.medium,
    },
    createTypeScreen: { paddingBottom: 40 },
    habitTypeRow: {
      flexDirection: 'row',
      gap: spacing.medium,
      marginTop: spacing.xl,
    },
    habitTypeCard: {
      flex: 1,
      minHeight: 142,
      alignItems: 'center',
      justifyContent: 'center',
      gap: spacing.large,
      paddingHorizontal: spacing.xs,
      borderRadius: radii.card,
      backgroundColor: colors.surfaceSecondary,
    },
    habitTypeCardActive: { backgroundColor: colors.primary },
    habitTypeNegative: { backgroundColor: colors.red },
    habitTypeLabel: {
      ...typography.caption,
      color: colors.textSecondary,
      fontWeight: '800',
      textAlign: 'center',
    },
    habitTypeDescription: {
      minHeight: 142,
      padding: spacing.xl,
      borderRadius: radii.card,
      backgroundColor: colors.surfaceSecondary,
      marginTop: spacing.xl,
    },
    habitTypeDescriptionTitle: {
      ...typography.headingM,
      color: colors.text,
      fontWeight: '700',
    },
    habitTypeDescriptionText: {
      ...typography.body,
      color: colors.textSecondary,
      marginTop: spacing.medium,
    },
    createOwnButton: { marginTop: spacing.xl },
    formIntro: {
      ...typography.body,
      color: colors.textSecondary,
      marginBottom: spacing.small,
    },
    label: {
      ...typography.caption,
      color: colors.textSecondary,
      fontWeight: '700',
      letterSpacing: 1,
    },
    appearanceCard: {
      overflow: 'hidden',
      borderRadius: radii.card,
      backgroundColor: colors.surfaceSecondary,
    },
    appearanceRow: {
      minHeight: 68,
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.medium,
      paddingHorizontal: spacing.large,
    },
    appearancePreview: {
      width: 40,
      height: 40,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 14,
    },
    appearanceLabel: {
      ...typography.bodyLarge,
      color: colors.text,
      flex: 1,
    },
    appearanceDivider: {
      height: StyleSheet.hairlineWidth,
      backgroundColor: colors.divider,
      marginLeft: 68,
      marginRight: spacing.large,
    },
    colorPreview: { width: 28, height: 28, borderRadius: 14 },
    formRowCard: {
      minHeight: 72,
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.medium,
      paddingHorizontal: spacing.large,
      borderRadius: radii.button,
      backgroundColor: colors.surfaceSecondary,
    },
    formRowLabel: {
      ...typography.bodyLarge,
      color: colors.text,
      flex: 1,
    },
    formRowValue: {
      ...typography.body,
      color: colors.textSecondary,
      maxWidth: '42%',
    },
    createTimeGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: spacing.medium,
    },
    createTimeOption: {
      width: '48%',
      minHeight: 56,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: radii.button,
      backgroundColor: colors.surfaceSecondary,
    },
    createTimeText: {
      ...typography.bodyLarge,
      color: colors.textSecondary,
    },
    goalModeRow: { flexDirection: 'row', gap: spacing.small },
    goalModeButton: {
      flex: 1,
      minHeight: 48,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: radii.button,
      backgroundColor: colors.surfaceSecondary,
    },
    goalTargetCard: {
      minHeight: 68,
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.medium,
      padding: spacing.medium,
      borderRadius: radii.button,
      backgroundColor: colors.surfaceSecondary,
    },
    smallStepButton: {
      width: 36,
      height: 36,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 18,
      backgroundColor: colors.divider,
    },
    goalTargetValue: {
      ...typography.bodyLarge,
      color: colors.text,
      minWidth: 70,
      textAlign: 'center',
    },
    advancedHeader: {
      minHeight: 48,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    advancedTitle: { ...typography.headingM, color: colors.text },
    advancedChevronOpen: { transform: [{ rotate: '180deg' }] },
    advancedContent: { gap: spacing.large },
    formError: {
      ...typography.caption,
      color: colors.red,
      marginTop: spacing.small,
    },
    createSheetBackdrop: {
      flex: 1,
      backgroundColor: colors.overlay,
      justifyContent: 'flex-end',
    },
    createSheetDismiss: { flex: 1 },
    createSheet: {
      maxHeight: '86%',
      padding: spacing.screen,
      paddingBottom: 38,
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      backgroundColor: colors.surface,
    },
    createSheetHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: spacing.large,
    },
    createSheetOptions: { gap: spacing.small },
    createSheetOption: {
      minHeight: 56,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: spacing.large,
      borderRadius: radii.button,
      backgroundColor: colors.surfaceSecondary,
    },
    createSheetOptionActive: { borderWidth: 1, borderColor: colors.primary },
    createSheetOptionText: { ...typography.bodyLarge, color: colors.text },
    createRadio: {
      width: 26,
      height: 26,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 2,
      borderColor: colors.muted,
      borderRadius: 13,
    },
    createRadioActive: {
      borderColor: colors.primary,
      backgroundColor: colors.primary,
    },
    weekdayPicker: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginTop: spacing.large,
    },
    weekdayButton: {
      width: 38,
      height: 44,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: radii.small,
      backgroundColor: colors.surfaceSecondary,
    },
    weekdayButtonActive: { backgroundColor: colors.primary },
    weekdayButtonText: {
      ...typography.bodyLarge,
      color: colors.textSecondary,
    },
    quotaPicker: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: spacing.xl,
      marginTop: spacing.xl,
    },
    quotaButton: {
      width: 48,
      height: 48,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 24,
      backgroundColor: colors.surfaceSecondary,
    },
    quotaValueGroup: { alignItems: 'center', minWidth: 110 },
    quotaValue: { ...typography.metric, color: colors.text },
    quotaCaption: { ...typography.caption, color: colors.textSecondary },
    createSheetActions: {
      flexDirection: 'row',
      gap: spacing.medium,
      marginTop: spacing.xl,
    },
    createSheetAction: { flex: 1 },
    datePickerRow: { gap: spacing.small, paddingVertical: spacing.small },
    datePickerOption: {
      width: 96,
      minHeight: 86,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: radii.button,
      backgroundColor: colors.surfaceSecondary,
    },
    datePickerOptionActive: { backgroundColor: colors.primary },
    datePickerDay: {
      ...typography.caption,
      color: colors.textSecondary,
      fontWeight: '700',
    },
    datePickerDate: {
      ...typography.body,
      color: colors.text,
      marginTop: spacing.small,
    },
    iconPickerGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: spacing.medium,
    },
    iconPickerOption: {
      width: 52,
      height: 52,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: radii.button,
      backgroundColor: colors.surfaceSecondary,
    },
    iconPickerOptionActive: { backgroundColor: colors.primary },
    colorPickerGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
      gap: spacing.large,
    },
    colorPickerOption: {
      width: 62,
      height: 62,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: radii.card,
    },
    colorPickerOptionActive: {
      borderWidth: 4,
      borderColor: colors.onPrimarySubtle,
    },
    iconOptions: { height: 50 },
    iconOption: {
      width: 50,
      height: 50,
      borderRadius: 15,
      backgroundColor: colors.surfaceSecondary,
      alignItems: 'center',
      justifyContent: 'center',
      marginHorizontal: 4,
    },
    iconActive: { backgroundColor: colors.selectedBlue },
    timeGrid: { height: TIME_OPTION_ROW_HEIGHT * 2, marginHorizontal: -4 },
    frequencyOptions: {
      height: TIME_OPTION_ROW_HEIGHT,
      marginHorizontal: -4,
    },
    timeOptionCell: { flex: 1, padding: spacing.xs },
    timeOption: {
      width: '100%',
      height: TIME_OPTION_HEIGHT,
      backgroundColor: colors.surfaceSecondary,
      borderRadius: radii.small,
      alignItems: 'center',
      justifyContent: 'center',
    },
    timeActive: { backgroundColor: colors.selectedBlue },
    timeText: {
      ...typography.caption,
      color: colors.textSecondary,
      fontWeight: '700',
    },
    reminder: {
      minHeight: 72,
      flexDirection: 'row',
      alignItems: 'center',
      padding: spacing.medium,
      borderRadius: radii.button,
      backgroundColor: colors.surface,
    },
    reminderBody: {
      flex: 1,
      minHeight: 48,
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.medium,
    },
    reminderPressed: { opacity: 0.75 },
    reminderIcon: {
      width: 40,
      height: 40,
      borderRadius: 13,
      backgroundColor: colors.iconSurface,
      alignItems: 'center',
      justifyContent: 'center',
    },
    reminderCopy: { flex: 1 },
    reminderTitle: { ...typography.bodyLarge, color: colors.text },
    reminderHint: { ...typography.caption, color: colors.textSecondary },
    mockHint: { ...typography.caption, color: colors.muted },
    save: { marginTop: 'auto' },
    detailHero: {
      marginTop: spacing.large,
      borderRadius: 24,
      backgroundColor: colors.selectedBlue,
      padding: spacing.xl,
    },
    detailTitle: { ...typography.headingL, color: colors.onPrimary },
    detailTime: {
      ...typography.caption,
      color: colors.onPrimaryMuted,
      marginTop: spacing.small,
    },
    detailMetric: { marginTop: 48 },
    metricNumber: { ...typography.metric, color: colors.onPrimary },
    metricLabel: {
      ...typography.caption,
      color: colors.onPrimaryMuted,
      fontWeight: '700',
    },
    noteCard: {
      marginTop: spacing.large,
      padding: spacing.large,
      borderRadius: radii.card,
      backgroundColor: colors.surface,
      gap: spacing.small,
    },
    noteText: { ...typography.body, color: colors.text },
  });

export default function useStyles() {
  return useThemedStyles(createStyles);
}
