import { StyleSheet } from 'react-native';
import {
  radii,
  spacing,
  typography,
  type ThemeColors,
} from '../../constants/theme';
import { useThemedStyles } from '../../hooks/useThemedStyles';

const createStyles = (colors: ThemeColors) =>
  StyleSheet.create({
    headerPad: { paddingHorizontal: spacing.screen },
    todayTop: {
      minHeight: 92,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    eyebrow: {
      ...typography.caption,
      color: colors.primary,
      fontWeight: '700',
      letterSpacing: 1.4,
    },
    dateTitle: { ...typography.headingXL, color: colors.text },
    progressText: {
      ...typography.caption,
      color: colors.textSecondary,
      marginTop: 2,
    },
    plus: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: colors.primary,
      alignItems: 'center',
      justifyContent: 'center',
    },
    dateStrip: {
      height: 56,
      flexGrow: 0,
      flexShrink: 0,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderColor: colors.divider,
    },
    dateStripContent: { paddingHorizontal: spacing.small },
    dateCell: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 3,
      borderBottomWidth: 3,
      borderBottomColor: colors.transparent,
    },
    dateListCell: { flex: 0, height: '100%' },
    dateActive: { borderBottomColor: colors.primary },
    dayName: { fontSize: 10, color: colors.muted, fontWeight: '700' },
    dayNumber: { ...typography.bodyLarge, color: colors.textSecondary },
    dateProgressTrack: {
      width: 18,
      height: 3,
      overflow: 'hidden',
      borderRadius: 2,
      backgroundColor: colors.divider,
    },
    dateProgressFill: {
      height: 3,
      borderRadius: 2,
      backgroundColor: colors.yellow,
    },
    dateProgressPerfect: { backgroundColor: colors.green },
    activeText: { color: colors.text },
    accentActiveText: { color: colors.onPrimary },
    content: { paddingHorizontal: spacing.screen, paddingBottom: 110 },
    filterList: { height: 72 },
    filters: { paddingVertical: spacing.large },
    filter: {
      height: 40,
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.small,
      paddingHorizontal: spacing.medium,
      borderRadius: 20,
      backgroundColor: colors.surface,
    },
    filterActive: { backgroundColor: colors.selectedBlue },
    filterText: {
      ...typography.caption,
      color: colors.textSecondary,
      fontWeight: '700',
    },
    sectionRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: spacing.medium,
    },
    sectionTitle: {
      ...typography.bodyLarge,
      color: colors.text,
      letterSpacing: 1,
    },
    finishedSectionRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginTop: spacing.xl,
      paddingTop: spacing.large,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: colors.divider,
    },
    finishedSectionTitle: {
      ...typography.bodyLarge,
      color: colors.textSecondary,
      letterSpacing: 1,
    },
    count: { ...typography.caption, color: colors.textSecondary },
    skeletonCard: {
      minHeight: 84,
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.medium,
      padding: spacing.large,
      borderRadius: radii.card,
      backgroundColor: colors.surfaceSecondary,
      opacity: 0.72,
    },
    skeletonCheckbox: {
      width: 30,
      height: 30,
      borderRadius: 15,
      backgroundColor: colors.divider,
    },
    skeletonCopy: { flex: 1, gap: spacing.small },
    skeletonTitle: {
      width: '68%',
      height: 14,
      borderRadius: 7,
      backgroundColor: colors.divider,
    },
    skeletonSubtitle: {
      width: '34%',
      height: 10,
      borderRadius: 5,
      backgroundColor: colors.divider,
    },
    skeletonMenu: {
      width: 24,
      height: 8,
      borderRadius: 4,
      backgroundColor: colors.divider,
    },
    habitList: { flex: 1 },
    empty: { alignItems: 'center', paddingVertical: spacing.xxl },
    emptyTitle: {
      ...typography.headingM,
      color: colors.text,
      marginTop: spacing.medium,
    },
    emptyText: {
      ...typography.body,
      color: colors.textSecondary,
      marginTop: spacing.xs,
      textAlign: 'center',
    },
    create: { marginTop: spacing.xl },
    todayButtonContainer: {
      position: 'absolute',
      right: spacing.screen,
      bottom: spacing.large,
      zIndex: 10,
    },
    todayButton: {
      height: 44,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: spacing.xs,
      paddingHorizontal: spacing.large,
      borderRadius: radii.pill,
      backgroundColor: colors.darkBlue,
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.28,
      shadowRadius: 8,
      elevation: 8,
    },
    todayButtonPressed: { opacity: 0.82 },
    todayButtonText: {
      ...typography.body,
      color: colors.onPrimary,
      fontWeight: '700',
    },
    backdrop: { flex: 1, backgroundColor: colors.overlay },
    popover: {
      position: 'absolute',
      width: 190,
      padding: spacing.small,
      borderRadius: radii.button,
      backgroundColor: colors.surfaceSecondary,
      shadowColor: colors.shadow,
      shadowOpacity: 0.35,
      shadowRadius: 12,
      elevation: 12,
    },
    menuItem: {
      height: 48,
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.medium,
      paddingHorizontal: spacing.medium,
    },
    menuText: {
      ...typography.caption,
      color: colors.text,
      fontWeight: '700',
      letterSpacing: 0.7,
    },
    sheetBackdrop: {
      flex: 1,
      backgroundColor: colors.overlay,
      justifyContent: 'flex-end',
    },
    sheet: {
      padding: spacing.screen,
      paddingBottom: 38,
      gap: spacing.large,
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      backgroundColor: colors.surface,
    },
    sheetHandle: {
      width: 42,
      height: 4,
      alignSelf: 'center',
      borderRadius: 2,
      backgroundColor: colors.muted,
    },
    sheetTop: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    sheetTitle: { ...typography.headingM, color: colors.text },
    form: { paddingBottom: 40, gap: spacing.large },
    formIntro: {
      ...typography.body,
      color: colors.textSecondary,
      marginBottom: spacing.small,
    },
    label: {
      ...typography.caption,
      color: colors.textSecondary,
      fontWeight: '700',
      letterSpacing: 1,
    },
    iconOptions: { height: 50 },
    iconOption: {
      width: 50,
      height: 50,
      borderRadius: 15,
      backgroundColor: colors.surfaceSecondary,
      alignItems: 'center',
      justifyContent: 'center',
      marginHorizontal: 4,
    },
    iconActive: { backgroundColor: colors.selectedBlue },
    timeGrid: { height: 96, marginHorizontal: -4 },
    frequencyOptions: { height: 52, marginHorizontal: -4 },
    timeOptionCell: { flex: 1, padding: 4 },
    timeOption: {
      width: '100%',
      height: 44,
      backgroundColor: colors.surfaceSecondary,
      borderRadius: radii.small,
      alignItems: 'center',
      justifyContent: 'center',
    },
    timeActive: { backgroundColor: colors.selectedBlue },
    timeText: {
      ...typography.caption,
      color: colors.textSecondary,
      fontWeight: '700',
    },
    reminder: {
      minHeight: 72,
      flexDirection: 'row',
      alignItems: 'center',
      padding: spacing.medium,
      borderRadius: radii.button,
      backgroundColor: colors.surface,
    },
    reminderBody: {
      flex: 1,
      minHeight: 48,
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.medium,
    },
    reminderPressed: { opacity: 0.75 },
    reminderIcon: {
      width: 40,
      height: 40,
      borderRadius: 13,
      backgroundColor: colors.iconSurface,
      alignItems: 'center',
      justifyContent: 'center',
    },
    reminderCopy: { flex: 1 },
    reminderTitle: { ...typography.bodyLarge, color: colors.text },
    reminderHint: { ...typography.caption, color: colors.textSecondary },
    mockHint: { ...typography.caption, color: colors.muted },
    save: { marginTop: 'auto' },
    detailHero: {
      marginTop: spacing.large,
      borderRadius: 24,
      backgroundColor: colors.selectedBlue,
      padding: spacing.xl,
    },
    detailTitle: { ...typography.headingL, color: colors.onPrimary },
    detailTime: {
      ...typography.caption,
      color: colors.onPrimaryMuted,
      marginTop: spacing.small,
    },
    detailMetric: { marginTop: 48 },
    metricNumber: { ...typography.metric, color: colors.onPrimary },
    metricLabel: {
      ...typography.caption,
      color: colors.onPrimaryMuted,
      fontWeight: '700',
    },
    noteCard: {
      marginTop: spacing.large,
      padding: spacing.large,
      borderRadius: radii.card,
      backgroundColor: colors.surface,
      gap: spacing.small,
    },
    noteText: { ...typography.body, color: colors.text },
  });

export default function useStyles() {
  return useThemedStyles(createStyles);
}
