import { StyleSheet } from 'react-native';
import { colors, radii, spacing, typography } from '../../constants/theme';

const styles = StyleSheet.create({
  top: { height: 30, justifyContent: 'center' },
  backSpace: { width: 28 },
  heading: {
    ...typography.headingXL,
    color: colors.text,
    marginTop: spacing.small,
  },
  subtitle: {
    ...typography.body,
    color: colors.textSecondary,
    marginTop: spacing.small,
  },
  spacer: { flex: 1, minHeight: spacing.large },
  existing: {
    ...typography.caption,
    color: colors.textSecondary,
    textAlign: 'center',
    marginTop: spacing.large,
  },
  restore: {
    ...typography.body,
    color: colors.primary,
    textAlign: 'center',
    marginTop: spacing.xs,
    paddingBottom: spacing.large,
  },
  goalGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    rowGap: spacing.medium,
    marginTop: spacing.xl,
  },
  goalCard: {
    width: '48.2%',
    minHeight: 112,
    borderRadius: radii.button,
    backgroundColor: colors.surfaceSecondary,
    overflow: 'hidden',
  },
  goalSelected: { backgroundColor: colors.selectedBlue },
  goalPress: {
    flex: 1,
    justifyContent: 'center',
    gap: spacing.medium,
    padding: spacing.card,
  },
  goalTitle: { ...typography.bodyLarge, color: colors.text },
  checkBadge: {
    position: 'absolute',
    right: 10,
    top: 10,
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: colors.text,
    alignItems: 'center',
    justifyContent: 'center',
  },
  presetList: { gap: spacing.small, marginTop: spacing.large },
  preset: {
    height: 52,
    paddingHorizontal: spacing.large,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.medium,
    borderRadius: radii.button,
    backgroundColor: colors.surfaceSecondary,
  },
  presetActive: { backgroundColor: colors.selectedBlue },
  presetTitle: { ...typography.bodyLarge, color: colors.text, flex: 1 },
  or: {
    ...typography.caption,
    color: colors.textSecondary,
    textAlign: 'center',
    marginVertical: spacing.medium,
  },
  customRow: { flexDirection: 'row', alignItems: 'center' },
  customInput: {
    ...typography.body,
    color: colors.text,
    backgroundColor: colors.surfaceSecondary,
    borderRadius: radii.button,
    height: 52,
    paddingHorizontal: spacing.large,
    flex: 1,
    paddingRight: 52,
  },
  confirm: {
    position: 'absolute',
    right: 8,
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  firstActions: {
    flexDirection: 'row',
    gap: spacing.medium,
    marginTop: spacing.xl,
    paddingBottom: spacing.large,
  },
  flexButton: { flex: 1 },
  generator: { justifyContent: 'center', alignItems: 'center' },
  progressWrap: {
    width: 200,
    height: 200,
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: spacing.xxl,
  },
  percent: { ...typography.metric, color: colors.text, position: 'absolute' },
  generatorMessage: {
    ...typography.bodyLarge,
    color: colors.textSecondary,
    textAlign: 'center',
  },
  valueScreen: { paddingBottom: spacing.xl },
  hero: {
    marginTop: spacing.small,
    borderRadius: 28,
    backgroundColor: '#17243C',
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
  },
  heroGlow: {
    position: 'absolute',
    width: 240,
    height: 240,
    borderRadius: 120,
    backgroundColor: '#1E4A8A',
    opacity: 0.55,
  },
  heroPhone: {
    width: 130,
    height: 210,
    borderRadius: 26,
    borderWidth: 5,
    borderColor: '#6EA8FF',
    backgroundColor: colors.surface,
    alignItems: 'center',
    paddingTop: 34,
    transform: [{ rotate: '-7deg' }],
  },
  heroTick: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  heroLine: {
    width: 80,
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.surfaceSecondary,
    marginTop: 20,
  },
  heroLineShort: { width: 55, marginTop: 10 },
  sparkle: { position: 'absolute', right: 34, top: 35 },
  center: { textAlign: 'center' },
  benefits: { gap: spacing.medium, marginVertical: spacing.xl },
  benefit: { flexDirection: 'row', alignItems: 'center', gap: spacing.medium },
  benefitIcon: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: '#1A304D',
    alignItems: 'center',
    justifyContent: 'center',
  },
  benefitText: { ...typography.body, color: colors.text, flex: 1 },
});

export default styles;
