import { StyleSheet } from 'react-native';
import {
  radii,
  spacing,
  typography,
  type ThemeColors,
} from '../../../constants/theme';
import { useThemedStyles } from '../../../hooks/useThemedStyles';

const createStyles = (colors: ThemeColors) =>
  StyleSheet.create({
    card: {
      borderRadius: radii.card,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.divider,
      marginBottom: spacing.medium,
      overflow: 'hidden',
    },
    current: { borderColor: colors.primary, borderWidth: 2 },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.medium,
      padding: spacing.large,
      minHeight: 76,
    },
    rowRTL: { flexDirection: 'row-reverse' },
    textRTL: { textAlign: 'right', writingDirection: 'rtl' },
    dateColumn: {
      width: 68,
      minHeight: 68,
      flexShrink: 0,
      borderRadius: radii.small,
      backgroundColor: colors.surfaceSecondary,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: spacing.xs,
      paddingVertical: spacing.small,
      gap: spacing.xs,
    },
    dateMonth: {
      ...typography.caption,
      fontWeight: '800',
      color: colors.textSecondary,
      textAlign: 'center',
    },
    dateDay: {
      fontSize: 28,
      lineHeight: 32,
      fontWeight: '800',
      color: colors.text,
      textAlign: 'center',
    },
    copy: { flex: 1, minWidth: 0 },
    title: { ...typography.bodyLarge, color: colors.text },
    secondary: {
      ...typography.caption,
      color: colors.textSecondary,
      marginTop: spacing.xs,
    },
    status: {
      ...typography.caption,
      color: colors.primary,
      marginTop: spacing.xs,
    },
    body: {
      paddingHorizontal: spacing.medium,
      paddingBottom: spacing.medium,
      gap: spacing.small,
    },
    task: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.small,
      paddingVertical: spacing.medium,
      minHeight: 64,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderColor: colors.divider,
    },
    icon: {
      width: 36,
      height: 36,
      borderRadius: radii.small,
      backgroundColor: colors.iconSurface,
      alignItems: 'center',
      justifyContent: 'center',
    },
    check: {
      width: 28,
      height: 28,
      borderRadius: 8,
      borderWidth: 2,
      borderColor: colors.primary,
      alignItems: 'center',
      justifyContent: 'center',
    },
    checked: { backgroundColor: colors.primary },
    locked: { borderColor: colors.textSecondary },
    pressed: { opacity: 0.8 },
    gridCard: {
      padding: spacing.large,
      marginBottom: spacing.large,
      flexDirection: 'row',
      alignItems: 'center',
      borderRadius: radii.card,
      backgroundColor: colors.surface,
      gap: spacing.medium,
    },
    gridHeading: { flexBasis: 90, flexShrink: 1, alignItems: 'center' },
    number: { ...typography.headingL, color: colors.text },
    gridDivider: {
      width: StyleSheet.hairlineWidth,
      alignSelf: 'stretch',
      backgroundColor: colors.divider,
    },
    gridScroll: { flex: 1, minWidth: 0 },
    grid: { flexDirection: 'row', alignItems: 'flex-start', gap: 12 },
    cellWrapper: { alignItems: 'center', gap: 4 },
    gridDayLabel: {
      ...typography.caption,
      color: colors.textSecondary,
      textAlign: 'center',
    },
    cell: {
      width: 18,
      height: 18,
      borderWidth: 1,
      borderColor: colors.divider,
      borderRadius: 4,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.surfaceSecondary,
    },
    cellCurrent: { borderColor: colors.primary, borderWidth: 2 },
    cellFinished: { backgroundColor: colors.primary },
    cellFinishedText: {
      color: colors.onPrimary,
      fontSize: 12,
      lineHeight: 14,
    },
  });
export default function useStyles() {
  return useThemedStyles(createStyles);
}
